### ISSUE TITLE
Tesseract 4 support

### ISSUE THREAD

**Issue by bwakkie** [deajan/pmOCR#12]
Would it be much effort to add support for tesseract 4? (https://github.com/tesseract-ocr/tesseract)?

**Comment by deajan** [comment]
This shouldn't require rocket science to get working, but I definitly need to setup a test machine with Tesseract 4 first, because my work environnment (CentOS 7) ships with Tesseract 3.

**Comment by deajan** [comment]
Seems that tesseract 3 and 4 both use the same syntax.
I've fired up a test machine today, and could use tesseract 4 without further problems.
Renamed "tesseract3" to "tesseract" to remove ambiguous config name.

Would you like to have a test run with current git before I release a new version ?

**Comment by bwakkie** [comment]
Please release :) I will check back at a later date when I have to batch process my 1000+ pdfs

**Comment by deajan** [comment]
I'll release shortly.
In the meantime, you may already use git master for tesseract 4.X.

**Comment by deajan** [comment]
Released.
