### ISSUE TITLE
Add support for GNU Parallel

### ISSUE THREAD

**Issue by popnt** [deajan/pmOCR#6]
The batch and service modes of pmOCR seem like good candidates to integrate Parallel
- https://www.gnu.org/software/parallel/

I'm not sure which would be the best way to do it but I'd be willing collaborate on it

**Comment by deajan** [comment]
I already have a parallel job control function which is portable to bsd and mac.
It should be easy to send OCR function to background without using gnu parallel.

What's the purpose here ?
Is the purpose is to use tesseract on all cores (abbyyocr11 is already threaded) ?
Is the purpose to run on multiple computers ?

**Comment by popnt** [comment]
Yes, Tesseract does not support all cores by default, but your point that it running on multiple computers sounds very useful too!

**Comment by deajan** [comment]
It's called "poor man" ocr service, running on multiple cores should be enough :)

I've commited some quick and dirty parallel execution work.
Number of processes is set in config header.

Please test it and tell me if it works for you.

**Comment by popnt** [comment]
Just gave it a try and seems to work just fine..! I set the process limit to 3 on a system with 4 cores, I'll monitor if it uses more than 3 but so far it looks stable.

**Comment by deajan** [comment]
Commited what should become v1.5.
Fixes an issue introduced with parallel processing on filenames with spaces and adds a couple of options for tesseract. Feel free to update and test.
Also, feel free to tell me if you have other ideas for this script :)

**Comment by popnt** [comment]
tested v1.5 and runs well. Also integrated instructions to run a new instance as outlined in Issue-7, it all seems stable!
